name: custom_linter
description: A starting point for Dart libraries or applications.
version: 0.1.0
# repository: https://github.com/Vabiel/custom_linter

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  analyzer: ^7.3.0
  custom_lint_builder: ^0.7.5

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
